_BASE_: "../Base-BoxTeacher.yaml"
MODEL:
  #  WEIGHTS: "../../pretrained_models/MSRA-R-50.pkl"
  # WEIGHTS: "output/checkpoints/pretrained_backbone.pth"
  RESNETS:
    DEPTH: 50

OUTPUT_DIR: "output/boxteacher_r50_1x"
# OUTPUT_DIR: "output/boxteacher_r50_1x_test"

