MODEL:
  META_ARCHITECTURE: "BoxTeacher"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
    NUM_CLASSES: 1
  CONDINST:
    TOPK_PROPOSALS_PER_IM: 64
    MASK_BRANCH:
      OUT_CHANNELS: 16
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 10
    PAIRWISE:
      SIZE: 3
      DILATION: 2
      COLOR_THRESH: 0.3
DATASETS:
  TRAIN: ("ssmg_coco_train",)
  TEST: ("ssmg_coco_val",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  STEPS: (60000, 80000)
  # STEPS: (15000, 20000)
  # MAX_ITER: 30000
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 30000
TEST:
  EVAL_PERIOD: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

