MODEL:
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: [ "res3", "res4", "res5" ]
  FPN:
    IN_FEATURES: [ "res3", "res4", "res5" ]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
